USE GroupManagement;
GO

IF OBJECT_ID('PersonId_GroupID', 'U') IS NULL
BEGIN
CREATE TABLE [PersonId_GroupID] (
	Person_Id bigint NOT NULL,
	Group_Id bigint NOT NULL
)
END
GO

ALTER TABLE [PersonId_GroupID] WITH CHECK ADD CONSTRAINT [PersonId_GroupID_fk0] FOREIGN KEY ([Person_Id]) REFERENCES [Person]([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [PersonId_GroupID] CHECK CONSTRAINT [PersonId_GroupID_fk0]
GO

ALTER TABLE [PersonId_GroupID] WITH CHECK ADD CONSTRAINT [PersonId_GroupID_fk1] FOREIGN KEY ([Group_Id]) REFERENCES [Group]([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [PersonId_GroupID] CHECK CONSTRAINT [PersonId_GroupID_fk1]
GO

USE GroupManagement_Deleted;
GO

IF OBJECT_ID('PersonId_GroupID', 'U') IS NULL
BEGIN
CREATE TABLE [PersonId_GroupID] (
	Person_Id bigint NOT NULL,
	Group_Id bigint NOT NULL
)
END
GO

ALTER TABLE [PersonId_GroupID] WITH CHECK ADD CONSTRAINT [PersonId_GroupID_fk0] FOREIGN KEY ([Person_Id]) REFERENCES [Person]([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [PersonId_GroupID] CHECK CONSTRAINT [PersonId_GroupID_fk0]
GO

ALTER TABLE [PersonId_GroupID] WITH CHECK ADD CONSTRAINT [PersonId_GroupID_fk1] FOREIGN KEY ([Group_Id]) REFERENCES [Group]([Id])
ON UPDATE CASCADE
GO

ALTER TABLE [PersonId_GroupID] CHECK CONSTRAINT [PersonId_GroupID_fk1]
GO
